name: Set and Use Output

on:
  repository_dispatch:
    types: [run-ping]
jobs:
  set_output_job:
    runs-on: ubuntu-latest
    permissions:
      contents: readwrite
    steps:
      - name: Set Output Variable
        id: set_my_output
        run: |
          echo "::set-output name=my_output::Hello from output"

      - name: Use Output Variable
        run: |
          echo "My output value: ${{ steps.set_my_output.outputs.my_output }}"
