name: workflow_02
on: [repository_dispatch]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering Wokflow 2"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test         
        run: |
            echo 'test'
            curl -X POST https://api.github.com/repos/annamalaiponnusamy/repo_01/dispatches \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -u ${{ secrets.ACTIONS_KEY }} \
            --data '{"event_type": "Trigger Workflow1", "client_payload": { "repository": "test" }}'     
