name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:
  repository_dispatch:
   

jobs:
  job1:
   runs-on: ubuntu-latest
   outputs:
      output1: ${{ steps.trigger-step2.outputs.output1 }}
   steps:    
     - name: Fetch remote job output
       run: |
           curl -H "Authorization: Bearer ${{ secrets.ACTIONS_KEY }}" \
                https://api.github.com/repos/inContact/qa-aspf-lab-dynamic-autoscale/actions/runs/13026385289/jobs \
                 | jq '.jobs[] | .steps[] | .outputs'
