name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:
  repository_dispatch:
   

jobs:
  job1:
   runs-on: ubuntu-latest
   outputs:
      output1: ${{ steps.trigger-step2.outputs.output1 }}
   steps:    
    - name: Data Print
    - id: Data1        
      run: |     
           echo "Winsip id : 324343"
   
